#!/bin/bash
files=( "bris8" "bris4" "bris8_v5" "bris4_v5"  "select8" "select4")
for f in "${files[@]}"
do
  echo $f $1
  for run in {1..10}
  do
    echo $run
    ./$f.o $1 >> "log_${f}_$1"
  done
done
