#!/bin/bash
files=( "vb_encode_8bit_bris" "vb_encode_8bit_bris_v5" "vb_encode_4bit_byteoptimized" "vb_encode_8bit_byteoptimized" "vb_encode_4bit_bris_v5")
for f in "${files[@]}"
do
  echo $f $1
  for run in {1..100}
  do
    echo $run
    ./$f.o $1 >> "log_${f}_$1"
  done
done
